name: movie_reviews
description: "A new Flutter project."
publish_to: 'none'  # Hapus baris ini jika Anda ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Menyertakan batasan versi SDK Flutter yang lebih tepat

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Versi dependensi HTTP
  image_picker: ^0.8.5+3  # Versi terbaru untuk memilih gambar
  sqflite: ^2.0.0+4  # Untuk SQLite local database
  path_provider: ^2.0.10  # Untuk mengambil lokasi penyimpanan file lokal
  flutter_image_compress: ^2.4.0  # Mengupdate versi ke yang lebih baru

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Lints untuk memastikan standar kode yang baik

flutter:
  uses-material-design: true  # Mengaktifkan desain material
